name: linting
on: push  # yamllint disable-line rule:truthy

jobs:
  markdown-lint:
    name: markdown-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: avto-dev/markdown-lint@v1
      with:
        args: "**/*.md"
  yaml-lint:
    name: yaml-lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ibiqlik/action-yamllint@v1
